blank_issues_enabled: true

issue_templates:
  - name: ğŸ“Œ Feature Request
    description: Suggest a new idea or enhancement.
    labels: [feature, enhancement]
    file: feature_request.yml

  - name: ğŸ› Bug Report
    description: Report a bug or unexpected behavior.
    labels: [bug]
    file: bug_report.yml

  - name: ğŸ§¹ Refactor Request
    description: Suggest a refactor or improvement of existing code.
    labels: [refactor]
    file: refactor_request.yml

  - name: â“ Question
    description: Ask a question or seek clarification.
    labels: [question]
    file: question.yml
