blank_issues_enabled: true

contact_links:
  - name: ðŸ†˜ Ask for Help / Support
    url: https://github.com/Matyslgr/.github/blob/main/SUPPORT.md
    about: Having trouble using the project? Check our support channels before opening an issue.
